#---
#spring:
  #profiles:
    #active: peer1

server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone:
        http://${eureka.instance.hostname}:${server.port}/eureka/

#---
#spring:
  #profiles:
    #active: peer2

#server:
  #port: 8762
#eureka:
  #instance:
    #hostname: peer2
  #client:
    #register-with-eureka: false
    #fetch-registry: false
    #service-url:
      #defaultZone:
        #http://peer1:8761/eureka/